export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const ACTIVATION_FAIL='ACTIVATION_FAIL';
export const ACTIVATION_SUCCESS='ACTIVATION_SUCCESS';
export const SIGNUP_FAIL='SIGNUP_FAIL';
export const USER_LOADED_SUCCESS='LOGIN_USER_SUCCESS';
export const DETECTION_LOADED_SUCCESS='DETECTION_USER_SUCCESS';
export const DETECTION_LOADED_FAIL='DETECTION_USER_FAIL';
export const TRENDS_LOADED_SUCCESS='TRENDS_USER_SUCCESS';
export const TRENDS_LOADED_FAIL='TRENDS_USER_FAIL';
export const USER_LOADED_FAIL='LOGIN_USER_FAIL';
export const PASSWORD_RESET_SUCCESS='PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL='PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS='PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_COMFIRM_FAIL='PASSWORD_RESET_COMFIRM_FAIL';
export const AUTHENTICATED_SUCCESS='AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL='AUTHENTICATED_FAIL';
export const LOGOUT='LOGOUT';
export const UP='UP';
export const DOWN='DOWN';
export const POST_FAIL='POST_FAIL';
export const POST_SUCCESS='POST_SUCCESS';
export const UPDATE_FAIL='UPDATE_FAIL,';
export const UPDATE_SUCCESS='UPDATE_SUCCESS';
export const DELETE_SUCCESS='DELETE_SUCCESS';
export const DELETE_FAIL='DELETE_FAIL,';
export const PASSWORD_SUCCESS='PASSWORD_SUCCESS';
export const PASSWORD_FAIL='PASSWORD_FAIL,';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = "PROFILE_FAIL";



